/**
 * Seed rows for deck generation (name, numeric value, optional meta).
 * Values are approximate; images are assigned at generate time.
 */

export const ANIMALS_WEIGHT = [
  { name: "Blue whale", value: 140000, meta: "approx adult" },
  { name: "Fin whale", value: 57000 },
  { name: "Southern right whale", value: 80000 },
  { name: "Humpback whale", value: 30000 },
  { name: "Sperm whale", value: 35000 },
  { name: "Bowhead whale", value: 75000 },
  { name: "Sei whale", value: 28000 },
  { name: "Bryde's whale", value: 23000 },
  { name: "Gray whale", value: 15000 },
  { name: "Minke whale", value: 6000 },
  { name: "Orca", value: 5500 },
  { name: "Whale shark", value: 10000 },
  { name: "White rhinoceros", value: 2000 },
  { name: "Black rhinoceros", value: 1100 },
  { name: "Indian rhinoceros", value: 2100 },
  { name: "African bush elephant", value: 6000 },
  { name: "Asian elephant", value: 4000 },
  { name: "Hippopotamus", value: 1500 },
  { name: "Giraffe", value: 1200 },
  { name: "American bison", value: 900 },
  { name: "Water buffalo", value: 1000 },
  { name: "Gaur", value: 1000 },
  { name: "Wild yak", value: 500 },
  { name: "Moose", value: 450 },
  { name: "Saltwater crocodile", value: 500 },
  { name: "Nile crocodile", value: 410 },
  { name: "American alligator", value: 230 },
  { name: "Polar bear", value: 450 },
  { name: "Kodiak bear", value: 450 },
  { name: "Brown bear", value: 350 },
  { name: "American black bear", value: 150 },
  { name: "Lion", value: 190 },
  { name: "Tiger", value: 220 },
  { name: "Jaguar", value: 85 },
  { name: "Leopard", value: 65 },
  { name: "Cheetah", value: 50 },
  { name: "Gray wolf", value: 40 },
  { name: "Spotted hyena", value: 65 },
  { name: "Gorilla", value: 160 },
  { name: "Orangutan", value: 75 },
  { name: "Chimpanzee", value: 50 },
  { name: "Walrus", value: 1000 },
  { name: "Northern elephant seal", value: 2000 },
  { name: "Southern elephant seal", value: 2200 },
  { name: "Steller sea lion", value: 450 },
  { name: "Manatee", value: 450 },
  { name: "Dugong", value: 400 },
  { name: "Great white shark", value: 1100 },
  { name: "Tiger shark", value: 550 },
  { name: "Bull shark", value: 230 },
  { name: "Hammerhead shark", value: 230 },
  { name: "Manta ray", value: 1350 },
  { name: "Beluga whale", value: 1400 },
  { name: "Narwhal", value: 1600 },
  { name: "Dromedary camel", value: 500 },
  { name: "Bactrian camel", value: 650 },
  { name: "Domestic cattle (bull)", value: 650 },
  { name: "Domestic horse (draft)", value: 900 },
  { name: "Domestic pig", value: 120 },
  { name: "Domestic sheep", value: 70 },
  { name: "Domestic goat", value: 45 },
  { name: "Red deer", value: 200 },
  { name: "Elk (wapiti)", value: 320 },
  { name: "Musk ox", value: 350 },
  { name: "Bighorn sheep", value: 120 },
  { name: "Mountain gorilla", value: 160 },
  { name: "Mandrill", value: 25 },
  { name: "Baboon", value: 30 },
  { name: "Ostrich", value: 130 },
  { name: "Emu", value: 35 },
  { name: "Southern cassowary", value: 60 },
  { name: "Green anaconda", value: 100 },
  { name: "Reticulated python", value: 75 },
  { name: "Komodo dragon", value: 70 },
  { name: "Aldabra giant tortoise", value: 250 },
  { name: "Galápagos tortoise", value: 300 },
  { name: "American crocodile", value: 200 },
  { name: "Gharial", value: 250 },
  { name: "Giant Pacific octopus", value: 50 },
  { name: "Colossal squid", value: 500 },
  { name: "Atlantic bluefin tuna", value: 300 },
  { name: "Ocean sunfish", value: 1000 },
  { name: "Great barracuda", value: 9 },
  { name: "Marlin (blue)", value: 100 },
  { name: "Swordfish", value: 200 },
  { name: "Sturgeon (beluga)", value: 250 },
  { name: "Arapaima", value: 100 },
  { name: "Mekong giant catfish", value: 200 },
  { name: "Wels catfish", value: 100 },
  { name: "American bison (wood bison)", value: 1000 },
  { name: "European bison", value: 900 },
  { name: "Zebra (common)", value: 300 },
  { name: "White-tailed deer", value: 100 },
  { name: "Reindeer", value: 180 },
  { name: "Moose (Alaska)", value: 550 },
  { name: "Saiga antelope", value: 40 },
  { name: "Nilgai", value: 215 },
  { name: "Eland (common)", value: 600 },
  { name: "Greater kudu", value: 190 },
  { name: "Waterbuck", value: 230 },
  { name: "Hippopotamus (pygmy)", value: 250 },
  { name: "Tapir (Brazilian)", value: 250 },
  { name: "Capybara", value: 50 },
  { name: "Red kangaroo", value: 85 },
];

export const ANIMALS_HEIGHT = [
  { name: "Blue whale", value: 3000, meta: "length" },
  { name: "Fin whale", value: 2000, meta: "length" },
  { name: "Sperm whale", value: 1800, meta: "length" },
  { name: "Humpback whale", value: 1500, meta: "length" },
  { name: "Whale shark", value: 1200, meta: "length" },
  { name: "Giraffe", value: 550, meta: "shoulder height" },
  { name: "African bush elephant", value: 330, meta: "shoulder" },
  { name: "Asian elephant", value: 280, meta: "shoulder" },
  { name: "Ostrich", value: 250, meta: "standing" },
  { name: "Polar bear", value: 280, meta: "standing" },
  { name: "Brown bear", value: 250, meta: "standing" },
  { name: "Moose", value: 235, meta: "shoulder" },
  { name: "Camel (dromedary)", value: 210, meta: "shoulder" },
  { name: "Bactrian camel", value: 220, meta: "shoulder" },
  { name: "American bison", value: 190, meta: "shoulder" },
  { name: "Water buffalo", value: 180, meta: "shoulder" },
  { name: "Saltwater crocodile", value: 600, meta: "length" },
  { name: "Nile crocodile", value: 500, meta: "length" },
  { name: "Reticulated python", value: 700, meta: "length" },
  { name: "Green anaconda", value: 550, meta: "length" },
  { name: "Komodo dragon", value: 300, meta: "length" },
  { name: "Tiger", value: 110, meta: "shoulder" },
  { name: "Lion", value: 120, meta: "shoulder" },
  { name: "Gray wolf", value: 85, meta: "shoulder" },
  { name: "Great white shark", value: 600, meta: "length" },
  { name: "Orca", value: 800, meta: "length" },
  { name: "Walrus", value: 320, meta: "body" },
  { name: "Giraffe (newborn)", value: 180, meta: "shoulder" },
  { name: "Emu", value: 170, meta: "standing" },
  { name: "Southern cassowary", value: 170, meta: "standing" },
  { name: "Human (average adult)", value: 170, meta: "standing" },
  { name: "Domestic pig", value: 90, meta: "shoulder" },
  { name: "Domestic cattle", value: 150, meta: "shoulder" },
  { name: "Draft horse", value: 180, meta: "withers" },
  { name: "Riding horse", value: 160, meta: "withers" },
  { name: "Red deer", value: 120, meta: "shoulder" },
  { name: "Elk", value: 150, meta: "shoulder" },
  { name: "Zebra", value: 140, meta: "shoulder" },
  { name: "Gorilla (standing)", value: 170, meta: "knuckle-walk" },
  { name: "Chimpanzee (standing)", value: 120, meta: "approx" },
  { name: "Orangutan (armspan)", value: 240, meta: "span" },
  { name: "Giraffe calf", value: 180, meta: "shoulder" },
  { name: "Elephant seal (male)", value: 500, meta: "length" },
  { name: "Leopard", value: 70, meta: "shoulder" },
  { name: "Jaguar", value: 70, meta: "shoulder" },
  { name: "Cheetah", value: 80, meta: "shoulder" },
  { name: "Spotted hyena", value: 90, meta: "shoulder" },
  { name: "Black rhino", value: 160, meta: "shoulder" },
  { name: "White rhino", value: 180, meta: "shoulder" },
  { name: "Indian rhino", value: 170, meta: "shoulder" },
  { name: "Hippopotamus", value: 150, meta: "shoulder" },
  { name: "Pygmy hippo", value: 100, meta: "shoulder" },
  { name: "American alligator", value: 400, meta: "length" },
  { name: "American crocodile", value: 400, meta: "length" },
  { name: "Gharial", value: 500, meta: "length" },
  { name: "Saltwater croc (large)", value: 650, meta: "length" },
  { name: "King cobra", value: 550, meta: "length" },
  { name: "Boa constrictor", value: 400, meta: "length" },
  { name: "Burmese python", value: 500, meta: "length" },
  { name: "Aldabra tortoise", value: 120, meta: "shell length" },
  { name: "Galápagos tortoise", value: 150, meta: "shell length" },
  { name: "Ostrich chick", value: 25, meta: "standing" },
  { name: "Emu chick", value: 25, meta: "standing" },
  { name: "Domestic cat", value: 25, meta: "shoulder" },
  { name: "Domestic dog (Great Dane)", value: 80, meta: "shoulder" },
  { name: "Domestic dog (Chihuahua)", value: 20, meta: "shoulder" },
  { name: "European rabbit", value: 40, meta: "body length" },
  { name: "House mouse", value: 8, meta: "body" },
  { name: "Brown rat", value: 28, meta: "head-body" },
  { name: "Beaver", value: 80, meta: "length" },
  { name: "Red kangaroo (standing)", value: 180, meta: "standing" },
  { name: "Wallaby", value: 85, meta: "standing" },
  { name: "Llama", value: 120, meta: "shoulder" },
  { name: "Alpaca", value: 100, meta: "shoulder" },
  { name: "Dromedary (hump top)", value: 230, meta: "standing" },
  { name: "Reindeer", value: 150, meta: "shoulder" },
  { name: "Musk ox", value: 150, meta: "shoulder" },
  { name: "Bison calf", value: 120, meta: "shoulder" },
  { name: "Wild boar", value: 100, meta: "shoulder" },
  { name: "Warthog", value: 85, meta: "shoulder" },
  { name: "Tapir", value: 110, meta: "shoulder" },
  { name: "Capybara", value: 60, meta: "shoulder" },
  { name: "Manatee", value: 350, meta: "length" },
  { name: "Dugong", value: 300, meta: "length" },
  { name: "Narwhal (excl. tusk)", value: 500, meta: "length" },
  { name: "Beluga whale", value: 500, meta: "length" },
  { name: "Minke whale", value: 800, meta: "length" },
  { name: "Gray whale", value: 1200, meta: "length" },
  { name: "Bowhead whale", value: 1500, meta: "length" },
  { name: "Sei whale", value: 1800, meta: "length" },
  { name: "Bryde's whale", value: 1400, meta: "length" },
  { name: "Ocean sunfish", value: 330, meta: "length" },
  { name: "Blue marlin", value: 450, meta: "length" },
  { name: "Swordfish", value: 450, meta: "length" },
  { name: "Giant squid", value: 1300, meta: "length" },
  { name: "Colossal squid", value: 400, meta: "length" },
  { name: "Manta ray", value: 700, meta: "wingspan" },
  { name: "Tiger shark", value: 550, meta: "length" },
  { name: "Hammerhead shark", value: 430, meta: "length" },
  { name: "Bull shark", value: 340, meta: "length" },
  { name: "Arapaima", value: 250, meta: "length" },
  { name: "Sturgeon (beluga)", value: 700, meta: "length" },
  { name: "Wels catfish", value: 300, meta: "length" },
  { name: "Mekong giant catfish", value: 300, meta: "length" },
  { name: "Great barracuda", value: 200, meta: "length" },
  { name: "Atlantic bluefin tuna", value: 300, meta: "length" },
  { name: "Whale shark", value: 1200, meta: "length" },
];

export const NBA_PPG = [
  { name: "Michael Jordan", value: 30.12 },
  { name: "Wilt Chamberlain", value: 30.07 },
  { name: "Elgin Baylor", value: 27.36 },
  { name: "Kevin Durant", value: 27.28 },
  { name: "Jerry West", value: 27.03 },
  { name: "LeBron James", value: 27.02 },
  { name: "Allen Iverson", value: 26.66 },
  { name: "Joel Embiid", value: 27.01 },
  { name: "Bob Pettit", value: 26.36 },
  { name: "George Gervin", value: 26.18 },
  { name: "Oscar Robertson", value: 25.68 },
  { name: "Kobe Bryant", value: 25.02 },
  { name: "Karl Malone", value: 25.01 },
  { name: "Rick Barry", value: 24.78 },
  { name: "Stephen Curry", value: 24.82 },
  { name: "Larry Bird", value: 24.29 },
  { name: "Carmelo Anthony", value: 22.52 },
  { name: "Adrian Dantley", value: 24.27 },
  { name: "James Harden", value: 24.01 },
  { name: "Anthony Davis", value: 24.02 },
  { name: "Shaquille O'Neal", value: 23.69 },
  { name: "Giannis Antetokounmpo", value: 22.02 },
  { name: "Dwyane Wade", value: 22.01 },
  { name: "Damian Lillard", value: 25.15 },
  { name: "Devin Booker", value: 24.51 },
  { name: "Luka Dončić", value: 28.51 },
  { name: "Trae Young", value: 25.52 },
  { name: "Paul George", value: 20.31 },
  { name: "Russell Westbrook", value: 21.75 },
  { name: "Kyrie Irving", value: 23.41 },
  { name: "Kawhi Leonard", value: 19.02 },
  { name: "Tim Duncan", value: 19.01 },
  { name: "Dirk Nowitzki", value: 20.72 },
  { name: "Patrick Ewing", value: 21.03 },
  { name: "Hakeem Olajuwon", value: 21.77 },
  { name: "David Robinson", value: 21.06 },
  { name: "Charles Barkley", value: 22.14 },
  { name: "Julius Erving", value: 22.02 },
  { name: "John Havlicek", value: 20.78 },
  { name: "Paul Pierce", value: 19.72 },
  { name: "Ray Allen", value: 18.91 },
  { name: "Reggie Miller", value: 18.22 },
  { name: "Vince Carter", value: 16.72 },
  { name: "Tracy McGrady", value: 19.61 },
  { name: "Grant Hill", value: 16.72 },
  { name: "Chris Webber", value: 20.71 },
  { name: "Kevin Garnett", value: 17.81 },
  { name: "Pau Gasol", value: 17.02 },
  { name: "Tony Parker", value: 15.52 },
  { name: "Manu Ginóbili", value: 13.32 },
  { name: "Steve Nash", value: 14.32 },
  { name: "Jason Kidd", value: 12.61 },
  { name: "Gary Payton", value: 16.32 },
  { name: "Chris Paul", value: 17.52 },
  { name: "Deron Williams", value: 16.32 },
  { name: "John Stockton", value: 13.12 },
  { name: "Isiah Thomas", value: 19.22 },
  { name: "Magic Johnson", value: 19.52 },
  { name: "Bob Cousy", value: 18.42 },
  { name: "Bill Russell", value: 15.12 },
  { name: "Wes Unseld", value: 10.82 },
  { name: "Moses Malone", value: 20.32 },
  { name: "Artis Gilmore", value: 18.52 },
  { name: "Bob McAdoo", value: 22.12 },
  { name: "George Mikan", value: 23.12 },
  { name: "Dolph Schayes", value: 18.52 },
  { name: "Dominique Wilkins", value: 24.82 },
  { name: "Alex English", value: 21.52 },
  { name: "Bernard King", value: 22.52 },
  { name: "Chris Mullin", value: 18.22 },
  { name: "Mitch Richmond", value: 21.02 },
  { name: "Glen Rice", value: 18.32 },
  { name: "Peja Stojaković", value: 17.02 },
  { name: "Vlade Divac", value: 11.82 },
  { name: "Yao Ming", value: 19.02 },
  { name: "Amar'e Stoudemire", value: 18.92 },
  { name: "Blake Griffin", value: 19.12 },
  { name: "DeMar DeRozan", value: 21.12 },
  { name: "Jimmy Butler", value: 18.22 },
  { name: "Klay Thompson", value: 19.52 },
  { name: "Draymond Green", value: 8.72 },
  { name: "Nikola Jokić", value: 20.02 },
  { name: "Jayson Tatum", value: 23.41 },
  { name: "Jaylen Brown", value: 20.22 },
  { name: "Donovan Mitchell", value: 24.12 },
  { name: "Shai Gilgeous-Alexander", value: 24.32 },
  { name: "Anthony Edwards", value: 23.02 },
  { name: "Ja Morant", value: 21.12 },
  { name: "Zion Williamson", value: 24.02 },
  { name: "Tyrese Haliburton", value: 20.12 },
  { name: "De'Aaron Fox", value: 20.42 },
  { name: "Bradley Beal", value: 22.02 },
  { name: "Karl-Anthony Towns", value: 22.62 },
  { name: "Rudy Gobert", value: 12.42 },
  { name: "Bam Adebayo", value: 19.12 },
  { name: "Jrue Holiday", value: 16.42 },
  { name: "LaMelo Ball", value: 20.03 },
  { name: "Scottie Barnes", value: 15.32 },
  { name: "CJ McCollum", value: 19.52 },
  { name: "Dejounte Murray", value: 15.12 },
];
